# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fultter_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fultter_ios


  flutter_application_path = '../fluttermodule'
  eval(File.read(File.join(flutter_application_path, '.ios','Flutter', 'podhelper.rb')), binding)

end
